sudo: false

cache:
  directories:
    - elm-stuff/build-artifacts
    - tests/elm-stuff/build-artifacts
    - sysconfcpus

os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.19 TARGET_NODE_VERSION=node ELM_TEST_VERSION=0.19.0-beta4

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION
  - npm install -g elm-test@$ELM_TEST_VERSION

script:
  - elm make --yes && elm-test
